language: php

php:
  - 7.2.5
  - 7.3

env:
  - LARAVEL_VERSION=7.5.*  
  - LARAVEL_VERSION=8.0.*
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction         
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;  
  - composer update

script:
  - phpunit